workspace(name = "sample")

# Load the repository rule to download an http archive.
load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
)

# Download rules_haskell and make it accessible as "@rules_haskell".
http_archive(
    name = "rules_haskell",
    strip_prefix = "rules_haskell-0.13",
    urls = ["https://github.com/tweag/rules_haskell/archive/v0.13.tar.gz"],
    sha256 = "b4e2c00da9bc6668fa0404275fecfdb31beb700abdba0e029e74cacc388d94d6",
)

load(
    "@rules_haskell//haskell:repositories.bzl",
    "rules_haskell_dependencies",
)

# Setup all Bazel dependencies required by rules_haskell.
rules_haskell_dependencies()

load(
    "@rules_haskell//haskell:toolchain.bzl",
    "rules_haskell_toolchains",
)

# Download a GHC binary distribution from haskell.org and register it as a toolchain.
rules_haskell_toolchains()

load(
    "@rules_haskell//haskell:cabal.bzl",
    "stack_snapshot",
)

stack_snapshot(
    local_snapshot = "//:stack-snapshot.yaml",
    name = "stackage",
    packages = [
        "aeson",
        "base",
        "bytestring",
        "Cabal",
        "containers",
        "deriving-aeson",
        "filepath",
        "here",
        "hpack",
        "http-client",
        "http-client-tls",
        "http-types",
        "megaparsec",
        "prettyprinter",
        "process",
        "tasty",
        "tasty-hunit",
        "text",
        "xml-conduit",
    ],
    setup_deps = {
        "xml-conduit": ["cabal-doctest"],
    },
)
