name:                hazell
version:             0.1.0.0
github:              "matsubara0507/hazell"
license:             BSD3
author:              "MATSUBARA Nobutada"
maintainer:          "nobutada0507@gmail.com"
copyright:           "2021 MATSUBARA Nobutada"

extra-source-files:
- README.md
- ChangeLog.md
description:         Please see the README on GitHub at <https://github.com/matsubara0507/hazell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hpack
- prettyprinter

library:
  source-dirs: src

executables:
  hazell:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - hazell

tests:
  hazell-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hazell
