name: Test

on:
  pull_request: null
  push:
    branches:
    - main

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019]
        ghc: ["8.10.4"]

    steps:
    - uses: actions/checkout@v2

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v2.1.4
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/package.yaml') }}-${{ hashFiles('**/stack.yaml.lock') }}
        restore-keys: |
          ${{ runner.os }}-stack-
    - uses: haskell/actions/setup@v1.2
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: 'latest'

    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies
    - name: Test
      run: stack --system-ghc test

    - name: Exec application
      run: stack --system-ghc exec -- hazell example
